language: python
python:
- 3.7.9
install:
- pip install -r requirements.txt
before_script:
- python manage.py migrate
script:
- black --check .
- flake8 .
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA5KPGKBUHHHBLV5CC
    secure: "YkjZsLHbtxg/dibzynMv+T/fHblqUWQH+pmltIs1lSavi6UetT6mdo3SQKDkLM6T8QC45E7gKH+4b/FSsRfzsk+GkEM0mstMwi9Wdk0Fj/RZVaeghHlY+yb9rPnwkFTyp9+VlZsngOVX7p80zPaCom52h3+2XCcrgGapv0UXY21uP6HqVPDe0n8CuNfmyOsp+rEbp5n/4ZsyGI9uHmjhIcCC47dUbnu6J1WoPp7119+58Gj9FNcyL3MXGvwm0Eik8z5zJkZAjo+oEfnMDmPzjPmDwqTp2dAjiWp9Wk2xNZX8E1s7EHaBDB/y9cV9reff7CnTh2xv9rz8QWGjrDDlV17/UT1+l4RetPTtC2W4fhBlvhn2JDstQ0rbZ5QLzAEGnLUIVj0dYLzgqRDC5tqQWMQHCGU1XBELQvP9ZrBSRJ3XCqYqjijVc7cz0h5PS8EvYv83oQHUORJOYtx4/omJIyIkACnzwSeogVDz861HPkALQ3c2Eh/GddXF9hFNbPU5m1L2ZHton0K1/O9FNS35crKRNB6bpqm+440ytWvK+CUokGAfyE8Hx3RWVzduKFTVC9jBeu65QSM3KQvBPfODVVa/P6LvWsj1tCjFo6QxgLar/lJ3j8ZFSiDgOqMqyXmFfDDMF3mcvpZfU8gZzt5SeFwf9yEElaFWpdiZN+mcNrw="
  secret_access_key: uJXjS3djO1otv9yIa8fRa0pNjNiDQkeeM1fNkhTt
    secure: "ID+vJam/wzOxpe78mMwAx4zsDaMfT+Gr93jpzb9DrxH1H5UUxEywqbP+vHkXeuPQGj1urakR3GLgdvuouPcdE+9yewuHTz3qWSMNztOG2QLAVcKCu3f8B0U40R7C6So1ePLuXOgfqXsT2P3iO1a9cAi0R5n9pMiILcPHEwjOov++xtLgbIzBhT9eTa9q1TbnJMKCT4dMDNS2+KevpwWikt1fv4OvU/quQChrsbhO+jPGbdqZgA1xN7F7PUvsSmYLPpaqLX9dAp+aF+1ZJ8e3UhMnW5UO6kQoAJvhduxaw+QL8qXxvSsuVd6Ge7qinN1niZ5vL8Py5RY2pt+2x+Qj0lJGBkAK9M2GPPsdwl5k6fDYQzM2GRHFtlypBEnHYX5gDJ0mC7a4TUHk48TIdGR5ehFt6tilsVcZlgxXJT8cC9OBYCfBgR3lqRbm5MNU58f1OJk4QTUL/XVD+MdrCPFY1r0rCUwWfv1QWakppAiq7U9pVkn2RaXDZ22IBJPCSdVIgyhCZ+QaS8/0lh9t0Z3TAbWnEJ+EMX7lLADsOwzwajs6bfmAh6Ne1V+snLJq30Fug1gB9Y8uHkb3+1HbjCOTS5rCpT8NhhVuFShDsPTqDLBPZJ+KaSD/58Y6CLPRIPpWie8bWZz4RiNatp0/KEKREpG2qp7i+PXWwhUD6rX74uY="
  region: us-east-1
  app: mycicdapp
  env: mycicdenv
  bucket_name: mysitecicd12-bucket
  on:
    all_branches: true
env:
  global:
 